export const images = {
  home: require('../assets/images/home.png'),
  homeButton: require('../assets/images/home_button.png'),
  storebutton: require('../assets/images/store_button.png'),
  store: require('../assets/images/store.png'),
  bell: require('../assets/images/bell.png'),
  menu: require('../assets/images/menu.png'),
  down: require('../assets/images/down.png'),
  search: require('../assets/images/search.png'),
  camera: require('../assets/images/camera.png'),
  profile: require('../assets/images/profile.png'),
  profile_button: require('../assets/images/profile_button.png'),
  heart: require('../assets/images/heart.png'),
  heart_button: require('../assets/images/heart_button.png'),
  shopping: require('../assets/images/shopping-bag.png'),
  shoping_button: require('../assets/images/shopping_button.png'),
  close: require('../assets/images/close.png'),
  star: require('../assets/images/star.png'),
};
